export interface Strategy {
  id: number;
  title: string;
  titleKo: string;
  description: string;
  descriptionKo: string;
  details: string;
  detailsKo: string;
  icon: string;
  color: string;
  completed: boolean;
}

export const strategies: Strategy[] = [
  {
    id: 1,
    title: "Citation Work Delegation",
    titleKo: "인용 작업 위임",
    description: "Finding and organizing reliable sources",
    descriptionKo: "신뢰할 수 있는 출처 찾기 및 정리",
    detailsKo: "새로운 주제를 학습할 때, 먼저 신뢰할 수 있는 출처를 찾는 데 시간을 투자합니다. 이를 통해 정보의 신뢰성을 확보하고 학습의 기초를 다집니다. 주제와 관련된 학술 논문, 서적, 신뢰할 수 있는 웹사이트를 검색하고, 각 출처의 신뢰도를 평가합니다.",
    details: "Finding and organizing reliable sources for your learning journey. This foundational step ensures information quality and builds a strong knowledge base.",
    icon: "📚",
    color: "coral",
    completed: false,
  },
  {
    id: 2,
    title: "Quick Topic Grasp",
    titleKo: "새로운 주제에 대한 빠른 파악",
    description: "Understanding the overall outline first",
    descriptionKo: "전체 윤곽을 먼저 파악하기",
    detailsKo: "새로운 주제를 접할 때, 전체 윤곽을 먼저 파악한 후 세부 사항으로 들어갑니다. 주제의 기본 정의와 역사를 학습하고, 주요 개념 및 용어를 정리하며, 관련 분야와의 연결고리를 파악합니다.",
    details: "Start by grasping the big picture before diving into details. This approach sets the direction for your learning and increases efficiency.",
    icon: "🎯",
    color: "mint",
    completed: false,
  },
  {
    id: 3,
    title: "Source Roadmap",
    titleKo: "관련 소스 로드맵 가져오기",
    description: "Creating a systematic learning path",
    descriptionKo: "체계적인 학습 경로 설정",
    detailsKo: "주제 학습에 필요한 모든 자료를 체계적으로 정렬하여 학습 경로를 설정합니다. 기초 개념부터 고급 개념까지 순서대로 배열하고, 각 단계별 학습 자료를 선정하며, 학습 시간 및 난이도를 예측합니다.",
    details: "Arrange all learning materials in a logical sequence from basic to advanced concepts. This maximizes learning efficiency and prevents confusion.",
    icon: "🗺️",
    color: "coral",
    completed: false,
  },
  {
    id: 4,
    title: "Concrete Questions",
    titleKo: "구체적인 질문을 하여 이해를 완성하기",
    description: "Deepening understanding through questioning",
    descriptionKo: "질문을 통한 이해 심화",
    detailsKo: "학습 과정에서 구체적이고 명확한 질문을 던짐으로써 이해의 깊이를 높입니다. '왜?'와 '어떻게?'로 시작하는 질문을 작성하고, 개념 간의 관계를 묻는 질문, 실제 적용 사례를 묻는 질문을 합니다.",
    details: "Ask specific and clear questions to move beyond surface-level understanding. Use 'why' and 'how' questions to explore deeper connections.",
    icon: "❓",
    color: "mint",
    completed: false,
  },
  {
    id: 5,
    title: "Outline Feedback",
    titleKo: "개요에 대한 피드백을 받아 흐름을 개선하기",
    description: "Improving logic through external feedback",
    descriptionKo: "외부 피드백을 통한 논리 개선",
    detailsKo: "학습한 내용을 개요로 정리한 후, 타인의 피드백을 통해 논리적 흐름을 개선합니다. 학습 내용을 개요 형식으로 정리하고, 전문가나 동료에게 피드백을 요청하며, 피드백을 바탕으로 개요를 수정 및 보완합니다.",
    details: "Organize your learning into an outline and seek feedback from others. This helps you evaluate your understanding objectively and strengthen logical thinking.",
    icon: "📝",
    color: "coral",
    completed: false,
  },
  {
    id: 6,
    title: "Reverse Outline",
    titleKo: "역개요로 논리 테스트 하기",
    description: "Testing logical consistency",
    descriptionKo: "논리적 일관성 검증",
    detailsKo: "작성한 글이나 정리한 내용을 역으로 분석하여 논리적 일관성을 검증합니다. 완성된 글의 각 문단에서 핵심 아이디어를 추출하고, 추출한 아이디어들의 논리적 연결을 확인하며, 빠진 부분이나 모순된 부분을 식별합니다.",
    details: "Analyze your writing in reverse to verify logical consistency. Extract key ideas and check for gaps or contradictions in your reasoning.",
    icon: "🔄",
    color: "mint",
    completed: false,
  },
  {
    id: 7,
    title: "Socratic Dialogue",
    titleKo: "소크라테스식 대화를 통해 아이디어를 개발하기",
    description: "Refining ideas through questioning",
    descriptionKo: "질문을 통한 아이디어 정교화",
    detailsKo: "질문과 답변의 반복을 통해 아이디어를 점진적으로 정교화합니다. 초기 아이디어를 제시하고, '그렇다면 왜 그럴까?', '다른 관점은?' 등의 질문을 던지며, 질문에 답하면서 아이디어를 개선하고 반복을 통해 아이디어를 심화합니다.",
    details: "Develop ideas through iterative questioning and answering. Move from surface-level understanding to fundamental insights.",
    icon: "💭",
    color: "coral",
    completed: false,
  },
  {
    id: 8,
    title: "Counter-Arguments",
    titleKo: "반론을 요청하여 논문에 대한 압력 테스트 수행하기",
    description: "Strengthening arguments through criticism",
    descriptionKo: "비판을 통한 주장 강화",
    detailsKo: "자신의 주장에 대한 반론을 적극적으로 찾고 검토하여 주장의 견고성을 확인합니다. 자신의 주장에 대한 가능한 반론을 생각해보고, 전문가나 동료에게 비판적 피드백을 요청하며, 반론에 대한 답변을 준비합니다.",
    details: "Actively seek counter-arguments to test your claims. Prepare responses and strengthen your position through critical examination.",
    icon: "⚔️",
    color: "mint",
    completed: false,
  },
  {
    id: 9,
    title: "Compare with Thinkers",
    titleKo: "당신의 아이디어를 역사상 가장 위대한 사상가들과 비교하기",
    description: "Contextualizing ideas historically",
    descriptionKo: "아이디어의 역사적 맥락화",
    detailsKo: "자신의 아이디어를 역사적 맥락에서 평가하고, 위대한 사상가들의 관점과 비교합니다. 관련 분야의 저명한 사상가 및 이론을 조사하고, 자신의 아이디어와 기존 이론의 공통점과 차이점을 분석하며, 자신의 아이디어가 기존 이론을 어떻게 발전시키는지 검토합니다.",
    details: "Evaluate your ideas in historical context and compare them with great thinkers. Understand where your ideas fit in the broader intellectual landscape.",
    icon: "🏛️",
    color: "coral",
    completed: false,
  },
  {
    id: 10,
    title: "Iterative Feedback",
    titleKo: "반복적인 피드백 활용",
    description: "Continuous improvement through cycles",
    descriptionKo: "반복적 개선을 통한 지속적 발전",
    detailsKo: "한 번의 피드백이 아닌 반복적인 피드백을 통해 지속적으로 개선합니다. 초기 버전을 작성하고 피드백을 수집하며, 피드백을 바탕으로 개선하고, 개선된 버전에 대한 추가 피드백을 요청하며, 반복 과정을 지속합니다.",
    details: "Embrace multiple rounds of feedback for continuous improvement. Each iteration brings you closer to excellence.",
    icon: "🔁",
    color: "mint",
    completed: false,
  },
  {
    id: 11,
    title: "Voice Learning",
    titleKo: "고급 음성 모드를 독서 동반자로 사용하기",
    description: "Multi-sensory learning approach",
    descriptionKo: "다감각 학습 방식",
    detailsKo: "텍스트 기반 학습에 음성 기술을 결합하여 다양한 학습 방식을 활용합니다. 학습 자료를 음성으로 재생하며 청취하고, 음성 기술을 활용한 실시간 질문 및 토론을 진행하며, 음성 기반 피드백을 수집합니다.",
    details: "Combine text and audio learning for a richer experience. Use voice technology to enhance comprehension and engage multiple senses.",
    icon: "🎙️",
    color: "coral",
    completed: false,
  },
];

export const colors = {
  coral: "oklch(0.75 0.20 15)",
  mint: "oklch(0.75 0.15 160)",
  purple: "oklch(0.65 0.15 290)",
  lavender: "oklch(0.97 0.002 290)",
};
